// studio/src/components/designer/DesignerGenerationToolbar.tsx
import { ChevronDownIcon, ImageIcon } from 'lucide-react'

import { QuantityStepper } from '@/components/agent-prompt/QuantityStepper'
import { Button } from '@/components/ui/button'
import { Popover, PopoverContent, PopoverTitle, PopoverTrigger } from '@/components/ui/popover'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import type { DesignerCapability, DesignerSettings } from '@/types/designer'
import type { DesignerSettingsPatch } from './DesignerToolbar'

interface DesignerGenerationToolbarProps {
  capabilities: DesignerCapability[]
  capabilityKey: string
  settings: DesignerSettings
  onCapabilityChange: (key: string) => void
  onSettingsChange: (patch: DesignerSettingsPatch) => void
  disabled?: boolean
}

const QUALITY_LABELS: Record<string, string> = {
  auto: '自动',
  low: '低',
  medium: '中',
  high: '高',
}

function settingLabel(value: string) {
  const fixedPreset = value.match(/^(\d+):(\d+):(1K|2K|4K)$/i)
  if (fixedPreset) {
    return `${fixedPreset[1]}:${fixedPreset[2]} · ${fixedPreset[3].toUpperCase()}`
  }
  return value
}

export function DesignerGenerationToolbar({
  capabilities,
  capabilityKey,
  settings,
  onCapabilityChange,
  onSettingsChange,
  disabled = false,
}: DesignerGenerationToolbarProps) {
  const selectedCapability = capabilities.find((capability) => capability.id === capabilityKey)
  const designerFeatures = selectedCapability?.designerFeatures
  const qualityLevels = designerFeatures?.qualityLevels ?? []
  const sizePresets = designerFeatures?.sizePresets ?? []
  const outputFormats = designerFeatures?.outputFormats ?? []
  const maxBatch = Math.max(1, designerFeatures?.maxBatch ?? 1)
  const summary = [
    selectedCapability?.name ?? '图像能力',
    settingLabel(settings.size),
    qualityLevels.length > 0 ? QUALITY_LABELS[settings.quality] ?? settings.quality : undefined,
    settings.outputFormat.toUpperCase(),
    `${settings.n} 张`,
  ].filter(Boolean).join(' · ')

  return (
    <Popover>
      <PopoverTrigger
        render={(
          <Button
            type="button"
            variant="ghost"
            size="sm"
            disabled={disabled || !selectedCapability}
            aria-label={`图像设置：${summary}`}
            className="max-w-full gap-1.5 px-2 text-muted-foreground"
          />
        )}
      >
        <ImageIcon data-icon="inline-start" />
        <span className="truncate">{summary}</span>
        <ChevronDownIcon data-icon="inline-end" />
      </PopoverTrigger>
      <PopoverContent align="start" className="max-h-[var(--available-height)] w-[min(24rem,calc(100vw-2rem))] gap-4 overflow-y-auto p-4">
        <section className="flex flex-col gap-2">
          <PopoverTitle>图像能力</PopoverTitle>
          <ToggleGroup
            aria-label="图像能力"
            value={capabilityKey ? [capabilityKey] : []}
            onValueChange={(next) => {
              if (next[0]) onCapabilityChange(next[0])
            }}
            variant="outline"
            className="flex w-full flex-col items-stretch"
          >
            {capabilities.map((capability) => (
              <ToggleGroupItem
                key={capability.id}
                value={capability.id}
                disabled={!capability.enabled || capability.priceAvailable !== true}
                className="h-auto min-h-14 w-full min-w-0 items-start justify-between gap-3 whitespace-normal px-3 py-2 text-left"
              >
                <span className="min-w-0">
                  <span className="block font-medium">{capability.name}</span>
                  {capability.description ? <span className="block text-xs text-muted-foreground">{capability.description}</span> : null}
                </span>
                <span className="shrink-0 text-xs text-muted-foreground">每张 {capability.credits.toLocaleString()} 积分</span>
              </ToggleGroupItem>
            ))}
          </ToggleGroup>
        </section>

        <section className="flex flex-col gap-2">
          <h3 className="font-medium">尺寸</h3>
          <ToggleGroup
            aria-label="尺寸"
            value={settings.size ? [settings.size] : []}
            onValueChange={(next) => {
              if (next[0]) onSettingsChange({ size: next[0] })
            }}
            variant="outline"
            size="sm"
            className="flex w-full flex-wrap justify-start"
          >
            {sizePresets.map((size) => (
              <ToggleGroupItem key={size} value={size}>{settingLabel(size)}</ToggleGroupItem>
            ))}
          </ToggleGroup>
        </section>

        {qualityLevels.length > 0 ? (
          <section className="flex flex-col gap-2">
            <h3 className="font-medium">质量</h3>
            <ToggleGroup
              aria-label="质量"
              value={settings.quality ? [settings.quality] : []}
              onValueChange={(next) => {
                if (next[0]) onSettingsChange({ quality: next[0] })
              }}
              variant="outline"
              size="sm"
              className="flex w-full flex-wrap justify-start"
            >
              {qualityLevels.map((quality) => (
                <ToggleGroupItem key={quality} value={quality}>{QUALITY_LABELS[quality] ?? quality}</ToggleGroupItem>
              ))}
            </ToggleGroup>
          </section>
        ) : null}

        <section className="flex flex-col gap-2">
          <h3 className="font-medium">输出格式</h3>
          <ToggleGroup
            aria-label="输出格式"
            value={settings.outputFormat ? [settings.outputFormat] : []}
            onValueChange={(next) => {
              if (next[0]) onSettingsChange({ outputFormat: next[0] })
            }}
            variant="outline"
            size="sm"
            className="flex w-full flex-wrap justify-start"
          >
            {outputFormats.map((format) => (
              <ToggleGroupItem key={format} value={format}>{format.toUpperCase()}</ToggleGroupItem>
            ))}
          </ToggleGroup>
        </section>

        <section className="flex justify-end">
          <QuantityStepper
            label="图片数量"
            value={settings.n}
            min={1}
            max={maxBatch}
            onChange={(n) => onSettingsChange({ n })}
            disabled={disabled}
          />
        </section>
      </PopoverContent>
    </Popover>
  )
}

// miniapp/src/components/business/DesignerGenerationToolbar.vue
<template>
  <view class="designer-toolbar">
    <view class="designer-toolbar__trigger" @tap="open = true">
      <AbIcon name="image" size="28rpx" />
      <text class="designer-toolbar__summary">{{ summary }}</text>
      <text class="designer-toolbar__arrow">›</text>
    </view>

    <view v-if="open" class="designer-sheet__mask" @tap="open = false" />
    <view class="designer-sheet" :class="{ 'designer-sheet--open': open }">
      <view class="designer-sheet__header">
        <text class="designer-sheet__title">生成设置</text>
        <text class="designer-sheet__close" @tap="open = false">完成</text>
      </view>
      <scroll-view scroll-y class="designer-sheet__body">
        <text class="designer-sheet__label">图像能力</text>
        <view
          v-for="capability in capabilities"
          :key="capability.id"
          class="designer-sheet__capability"
          :class="{ 'designer-sheet__capability--active': capabilityKey === capability.id }"
          @tap="selectCapability(capability.id)"
        >
          <text class="designer-sheet__capability-name">{{ capability.name }}</text>
          <text v-if="capability.description" class="designer-sheet__hint">{{ capability.description }}</text>
          <text class="designer-sheet__price">每张 {{ capability.credits.toLocaleString() }} 积分</text>
        </view>

        <template v-if="selectedCapability">
          <text class="designer-sheet__label designer-sheet__label--spaced">固定规格</text>
          <view class="designer-sheet__choices">
            <view
              v-for="preset in selectedCapability.designerFeatures.sizePresets"
              :key="preset"
              class="designer-sheet__choice"
              :class="{ 'designer-sheet__choice--active': settings.size === preset }"
              @tap="patchSettings({ size: preset })"
            >
              <text>{{ presetLabel(preset) }}</text>
            </view>
          </view>

          <template v-if="selectedCapability.designerFeatures.qualityLevels.length">
            <text class="designer-sheet__label designer-sheet__label--spaced">质量</text>
            <view class="designer-sheet__choices">
              <view
                v-for="quality in selectedCapability.designerFeatures.qualityLevels"
                :key="quality"
                class="designer-sheet__choice"
                :class="{ 'designer-sheet__choice--active': settings.quality === quality }"
                @tap="patchSettings({ quality })"
              >
                <text>{{ qualityLabel(quality) }}</text>
              </view>
            </view>
          </template>

          <text class="designer-sheet__label designer-sheet__label--spaced">格式</text>
          <view class="designer-sheet__choices">
            <view
              v-for="format in selectedCapability.designerFeatures.outputFormats"
              :key="format"
              class="designer-sheet__choice"
              :class="{ 'designer-sheet__choice--active': settings.outputFormat === format }"
              @tap="patchSettings({ outputFormat: format })"
            >
              <text>{{ format.toUpperCase() }}</text>
            </view>
          </view>

          <template v-if="selectedCapability.designerFeatures.maxBatch > 1">
            <text class="designer-sheet__label designer-sheet__label--spaced">图片数量</text>
            <view class="designer-sheet__choices">
              <view
                v-for="count in selectedCapability.designerFeatures.maxBatch"
                :key="count"
                class="designer-sheet__choice"
                :class="{ 'designer-sheet__choice--active': settings.n === count }"
                @tap="patchSettings({ n: count })"
              >
                <text>{{ count }}</text>
              </view>
            </view>
          </template>
        </template>
      </scroll-view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import type { DesignerCapability, DesignerSettings } from '@/types'
import AbIcon from '@/components/common/AbIcon.vue'

const props = defineProps<{
  capabilities: DesignerCapability[]
  capabilityKey: string
  settings: DesignerSettings
}>()
const emit = defineEmits<{
  (event: 'update:capabilityKey', value: string): void
  (event: 'update:settings', value: DesignerSettings): void
}>()
const open = ref(false)

const selectedCapability = computed(() => props.capabilities.find((item) => item.id === props.capabilityKey))
const summary = computed(() => [
  selectedCapability.value?.name || '图像能力',
  presetLabel(props.settings.size),
  props.settings.quality ? qualityLabel(props.settings.quality) : '',
].filter(Boolean).join(' · '))

function presetLabel(preset: string): string {
  const parts = preset.split(':')
  if (parts.length === 3) return `${parts[0]}:${parts[1]} · ${parts[2].toUpperCase()}`
  return preset
}

function qualityLabel(quality: string): string {
  return ({ auto: '自动', low: '低', medium: '中', high: '高' } as Record<string, string>)[quality] || quality
}

function selectCapability(value: string) {
  emit('update:capabilityKey', value)
}

function patchSettings(patch: Partial<DesignerSettings>) {
  emit('update:settings', { ...props.settings, ...patch })
}
</script>

<style lang="scss" scoped>
.designer-toolbar { margin-top: $ab-space-xs; }
.designer-toolbar__trigger { display: inline-flex; align-items: center; max-width: 100%; min-height: 60rpx; gap: 10rpx; padding: 0 $ab-space-sm; border-radius: $ab-radius-sm; color: $ab-text-secondary; }
.designer-toolbar__summary { min-width: 0; overflow: hidden; color: $ab-text-secondary; font-size: $ab-text-sm; text-overflow: ellipsis; white-space: nowrap; }
.designer-toolbar__arrow { color: $ab-text-tertiary; font-size: $ab-text-lg; }
.designer-sheet__mask { position: fixed; inset: 0; z-index: 80; background: rgba(0, 0, 0, 0.42); }
.designer-sheet { position: fixed; right: 0; bottom: 0; left: 0; z-index: 81; padding: $ab-space-md $ab-space-md calc(#{$ab-space-md} + env(safe-area-inset-bottom)); border-radius: 16rpx 16rpx 0 0; background: $ab-surface; transform: translateY(110%); transition: transform 180ms ease; }
.designer-sheet--open { transform: translateY(0); }
.designer-sheet__header { display: flex; align-items: center; justify-content: space-between; margin-bottom: $ab-space-md; }
.designer-sheet__title { color: $ab-text; font-size: $ab-text-lg; font-weight: $ab-font-semibold; }
.designer-sheet__close { color: $ab-primary; font-size: $ab-text-sm; }
.designer-sheet__body { max-height: 70vh; }
.designer-sheet__label { display: block; margin-bottom: $ab-space-sm; color: $ab-text; font-size: $ab-text-sm; font-weight: $ab-font-medium; }
.designer-sheet__label--spaced { margin-top: $ab-space-lg; }
.designer-sheet__capability { margin-bottom: $ab-space-sm; padding: $ab-space-sm $ab-space-md; border: 2rpx solid $ab-border; border-radius: $ab-radius-sm; }
.designer-sheet__capability--active { border-color: $ab-primary; background: $ab-primary-bg; }
.designer-sheet__capability-name, .designer-sheet__hint, .designer-sheet__price { display: block; }
.designer-sheet__capability-name { color: $ab-text; font-size: $ab-text-base; font-weight: $ab-font-medium; }
.designer-sheet__hint { margin-top: 6rpx; color: $ab-text-secondary; font-size: $ab-text-sm; line-height: 1.4; }
.designer-sheet__price { margin-top: 6rpx; color: $ab-text; font-size: $ab-text-sm; font-weight: $ab-font-medium; }
.designer-sheet__choices { display: flex; flex-wrap: wrap; gap: $ab-space-sm; }
.designer-sheet__choice { min-width: 112rpx; padding: 14rpx $ab-space-sm; border: 2rpx solid $ab-border; border-radius: $ab-radius-sm; color: $ab-text-secondary; font-size: $ab-text-sm; text-align: center; }
.designer-sheet__choice--active { border-color: $ab-primary; background: $ab-primary-bg; color: $ab-primary; }
</style>
