// studio/src/components/tasks/ExecutionProfileSelector.tsx
import { Badge } from '@/components/ui/badge'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Skeleton } from '@/components/ui/skeleton'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { ChevronDown } from 'lucide-react'
import type { AgentExecutionProfileCapability, AgentExecutionProfileID, AgentModelMatrix } from '@/types'

const minimumTierLabel = {
  free: '全部用户',
  pro: 'Pro 版及以上',
  enterprise: '企业版',
} as const

const unavailableReasonLabel: Record<string, string> = {
  requires_pro: '需要 Pro 版或企业版',
  requires_enterprise: '需要企业版',
  profile_configuration_missing: '当前档位尚未配置',
  agent_provider_unavailable: '当前模型服务不可用',
  agent_model_cost_unmapped: '当前模型尚未配置成本',
}

const modelRoles: Array<[keyof AgentModelMatrix, string]> = [
  ['default', '默认'],
  ['opus', 'Opus'],
  ['fable', 'Fable'],
  ['sonnet', 'Sonnet'],
  ['haiku', 'Haiku'],
]

function uniformModel(models: AgentModelMatrix): string | undefined {
  const values = Object.values(models)
  return values.every((model) => model === values[0]) ? values[0] : undefined
}

function unavailableReason(profile: AgentExecutionProfileCapability): string {
  const reason = profile.unavailable_reason || ''
  return unavailableReasonLabel[reason] || reason || '当前不可用'
}

export interface ExecutionProfileSelectorProps {
  profiles: AgentExecutionProfileCapability[]
  value: AgentExecutionProfileID | ''
  onChange: (value: AgentExecutionProfileID) => void
  loading?: boolean
  disabled?: boolean
}

export function ExecutionProfileSelector({
  profiles,
  value,
  onChange,
  loading = false,
  disabled = false,
}: ExecutionProfileSelectorProps) {
  if (loading) {
    return (
      <div className="grid grid-cols-1 gap-2 sm:grid-cols-3" aria-label="正在加载执行配置">
        {[0, 1, 2].map((index) => <Skeleton key={index} className="h-24 w-full" />)}
      </div>
    )
  }

  return (
    <ToggleGroup
      aria-label="Agent 执行配置"
      className="grid w-full grid-cols-1 items-stretch gap-2 sm:grid-cols-3"
      value={value ? [value] : []}
      onValueChange={(next) => {
        const selected = next[0] as AgentExecutionProfileID | undefined
        if (selected) onChange(selected)
      }}
      variant="outline"
      disabled={disabled}
    >
      {profiles.map((profile) => {
        const reason = unavailableReason(profile)
        const uniform = uniformModel(profile.models)
        return (
          <Collapsible key={profile.id} className="min-w-0">
            <ToggleGroupItem
              value={profile.id}
              disabled={!profile.available}
              aria-label={`${profile.display_name}，${profile.provider}，${profile.models.default}，${minimumTierLabel[profile.min_tier]}${profile.available ? '' : `，不可用：${reason}`}`}
              className="h-auto min-h-24 w-full min-w-0 flex-col items-start justify-start gap-1 whitespace-normal px-3 py-2 text-left"
            >
              <span className="flex w-full items-center justify-between gap-2">
                <span className="font-medium">{profile.display_name}</span>
                <span className="flex shrink-0 items-center gap-1">
                  <Badge variant="outline">{minimumTierLabel[profile.min_tier]}</Badge>
                  {!profile.available ? <Badge variant="secondary">不可用</Badge> : null}
                </span>
              </span>
              <span className="text-xs text-muted-foreground">{profile.provider}</span>
              <span className="break-all font-mono text-[11px] text-muted-foreground">
                {uniform ? `全部角色：${uniform}` : `默认：${profile.models.default}`}
              </span>
              <span className="text-xs text-muted-foreground">
                {profile.available ? profile.description : reason}
              </span>
            </ToggleGroupItem>
            {!uniform ? (
              <>
                <CollapsibleTrigger
                  aria-label={`查看${profile.display_name}模型配置`}
                  title="查看模型配置"
                  className="mt-1 flex size-7 items-center justify-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"
                >
                  <ChevronDown className="size-4 transition-transform in-data-[panel-open]:rotate-180" />
                </CollapsibleTrigger>
                <CollapsibleContent className="pt-1">
                  <div className="space-y-1 border-l border-border pl-2 text-[11px] text-muted-foreground">
                    {modelRoles.slice(1).map(([role, label]) => (
                      <div key={role} className="break-all font-mono">{label}：{profile.models[role]}</div>
                    ))}
                  </div>
                </CollapsibleContent>
              </>
            ) : null}
          </Collapsible>
        )
      })}
    </ToggleGroup>
  )
}

// miniapp/src/components/business/ExecutionProfileSelector.vue
<template>
  <view class="profile-selector">
    <view v-if="loading" class="profile-selector__loading">
      <text>正在加载执行配置...</text>
    </view>
    <template v-else>
      <view
        v-for="profile in profiles"
        :key="profile.id"
        class="profile-card"
        :class="{
          'profile-card--active': modelValue === profile.id,
          'profile-card--disabled': !profile.available || disabled,
        }"
        @tap="selectProfile(profile)"
      >
        <view class="profile-card__header">
          <text class="profile-card__name">{{ profile.display_name }}</text>
          <text v-if="!profile.available" class="profile-card__badge">不可用</text>
        </view>
        <text class="profile-card__provider">Provider：{{ profile.provider }}</text>
        <text
          v-for="row in modelRows(profile)"
          :key="row"
          class="profile-card__model"
        >
          {{ row }}
        </text>
        <text class="profile-card__tier">{{ tierRequirement(profile.min_tier) }}</text>
        <text class="profile-card__description">
          {{ profile.available ? profile.description : unavailableReason(profile) }}
        </text>
      </view>
    </template>
  </view>
</template>

<script setup lang="ts">
import type {
  AgentExecutionProfileCapability,
  AgentExecutionProfileID,
  AgentModelMatrix,
} from '@/types'

const modelRoles: Array<[keyof AgentModelMatrix, string]> = [
  ['default', '默认'],
  ['opus', 'Opus'],
  ['fable', 'Fable'],
  ['sonnet', 'Sonnet'],
  ['haiku', 'Haiku'],
]

const props = withDefaults(defineProps<{
  modelValue: AgentExecutionProfileID | ''
  profiles: AgentExecutionProfileCapability[]
  loading?: boolean
  disabled?: boolean
}>(), {
  loading: false,
  disabled: false,
})

const emit = defineEmits<{
  (event: 'update:modelValue', value: AgentExecutionProfileID): void
}>()

function selectProfile(profile: AgentExecutionProfileCapability) {
  if (props.disabled || !profile.available) return
  emit('update:modelValue', profile.id)
}

function modelRows(profile: AgentExecutionProfileCapability): string[] {
  const values = [
    profile.models.default,
    profile.models.opus,
    profile.models.fable,
    profile.models.sonnet,
    profile.models.haiku,
  ]
  if (values.every((model) => model === values[0])) {
    return [`全部角色：${values[0]}`]
  }
  return modelRoles.map(([role, label]) => `${label}：${profile.models[role]}`)
}

function tierRequirement(tier: AgentExecutionProfileCapability['min_tier']) {
  if (tier === 'pro') return '最低套餐：Pro 版及以上'
  if (tier === 'enterprise') return '最低套餐：企业版'
  return '所有用户可用'
}

function unavailableReason(profile: AgentExecutionProfileCapability) {
  const reason = profile.unavailable_reason
  if (reason === 'requires_pro') return '需要 Pro 套餐'
  if (reason === 'requires_enterprise') return '需要企业版套餐'
  if (reason === 'profile_configuration_missing') return '当前档位尚未配置'
  if (reason === 'agent_provider_unavailable') return '当前模型服务不可用'
  if (reason === 'agent_model_cost_unmapped') return '当前模型尚未配置成本'
  return reason || '当前不可用'
}
</script>

<style lang="scss" scoped>
.profile-selector {
  display: flex;
  flex-direction: column;
  gap: $ab-space-sm;

  &__loading {
    min-height: 160rpx;
    display: flex;
    align-items: center;
    justify-content: center;
    color: $ab-text-tertiary;
    font-size: $ab-text-sm;
  }
}

.profile-card {
  min-height: 144rpx;
  padding: $ab-space-sm $ab-space-md;
  border: 2rpx solid $ab-border;
  border-radius: $ab-radius-sm;
  background-color: $ab-surface;
  box-sizing: border-box;

  &--active {
    border-color: $ab-primary;
    background-color: $ab-primary-bg;
  }

  &--disabled {
    background-color: $ab-background;
    opacity: 0.68;
  }

  &__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: $ab-space-sm;
  }

  &__name {
    color: $ab-text;
    font-size: $ab-text-base;
    font-weight: $ab-font-medium;
  }

  &__badge {
    flex-shrink: 0;
    padding: 4rpx 12rpx;
    border-radius: $ab-radius-sm;
    color: $ab-text-tertiary;
    background-color: $ab-divider;
    font-size: $ab-text-xs;
  }

  &__provider,
  &__model,
  &__tier,
  &__description {
    display: block;
    margin-top: 8rpx;
    color: $ab-text-secondary;
    font-size: $ab-text-sm;
    line-height: 1.45;
  }

  &__description {
    color: $ab-text-tertiary;
  }

  &__model {
    font-family: monospace;
    font-size: $ab-text-xs;
    overflow-wrap: anywhere;
  }

  &__tier {
    color: $ab-text-secondary;
  }
}
</style>
